In [1]:
import numpy as np

from PIL import Image
import os, sys
import glob

In [2]:
os.environ['THEANO_FLAGS'] = "device=gpu"    
import theano
theano.config.device

Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5103)


'gpu'

In [3]:
from keras.models import Sequential
import numpy as np
import sklearn

Using Theano backend.


In [4]:
# The load_path function loads the .jpg image and converts it to a numpy array. 
# It also extracts the image label from path and places it into file_array
import os
from PIL import Image
import time

def load_data(paths):
    
    X = []
    file_array = []
    label_array = []
  
    # Images are resized because they range from 720-924 and 1192-1280 Making it difficult to use in models
    # and neural networks
    # Most 'common' original image size
    # The 'im.resize' switches these dimensions. That is why they are backwards here.
    size = 1280, 720
    
    print('..loading images')
    start = time.time()
    
    # if loading 'training set' also extract label from file
        
    for path in glob.glob(paths):

        try:
            # load image and convert to np array
            im = Image.open(path)
            im = im.resize((size[0], size[1]))
            im = np.asarray(im)
            X.append(im)

            # extract file name EX: img_00003.jpg
            base = os.path.basename(path)
            file_array.append(base)

            if 'train' in paths:
                # extract fish label (ALB, BET, DOL, LAG, NoF, OTEHR, SHARK, YFT)
                directory = os.path.split(path)[0]
                label_array.append(os.path.split(directory)[1])

        except IOError:
            print "cannot load or resize image for '%s'" % path


    print('time elapsed: ' + str(time.time() - start))

    if 'train' in paths:
        return X, file_array, label_array

    else:
        return X, file_array


In [5]:
# convert label_array containing m number of labels, in this case, 8 different types of fish, to a one-hot encoded array
def convert_to_one_hot(label_array):
    n = len(label_array) #number of samples
    m = 8 #number of types of fish
    
    classification_array = np.zeros(n)
 
    # assign numerical label to each type of fish
    for sample in xrange(n):
        
        if label_array[sample] == 'ALB':
            classification_array[sample] = 0
            
        elif label_array[sample] == 'BET':
            classification_array[sample] = 1
            
        elif label_array[sample] == 'DOL':
            classification_array[sample] = 2
        
        elif label_array[sample] == 'LAG':
            classification_array[sample] = 3
            
        elif label_array[sample] == 'NoF':
            classification_array[sample] = 4
            
        elif label_array[sample] == 'OTHER':
            classification_array[sample] = 5
            
        elif label_array[sample] == 'SHARK':
            classification_array[sample] = 6
            
        elif label_array[sample] == 'YFT':
            classification_array[sample] = 7
            
    # covert array to to one-hot encoded array        
    one_hot_array = np.eye(m)[classification_array.astype(int)]
            
    return classification_array, one_hot_array

In [6]:
from random import shuffle

def shuffle_X_and_Y(X, Y):
    # Given list X and list Y
    X_shuf = []
    Y_shuf = []
    index_shuf = range(len(X))
    shuffle(index_shuf)
    
    for i in index_shuf:
        X_shuf.append(X[i])
        Y_shuf.append(label_array[i])
        
    return(X_shuf, Y_shuf)

In [7]:
X, file_array, label_array = load_data('F:/Kaggle/The Nature Conservancy/train/train/*/*')

..loading images
time elapsed: 94.3899998665


In [8]:
classification_array, Y = convert_to_one_hot(label_array)

In [10]:
label_numbers = np.zeros(8)
for i in xrange(8):
    label_numbers[i] = np.sum(classification_array==i)

# try un-skewing data

In [11]:
X_unskew = []
label_unskew = []

index = 0
offset = 67
for i in xrange(8):
    for j in xrange(offset):
        X_unskew.append(X[int(index+j)])
        label_unskew.append(label_array[int(index+j)])
        #print(index+j)
    
    index += label_numbers[i]

# shuffle_X_and_Y causes all labels to become ALB

In [12]:
X, label_array = shuffle_X_and_Y(X, label_array)

In [13]:
X_unskew, label_unskew = shuffle_X_and_Y(X_unskew, label_unskew)

In [14]:
label_unskew

['ALB',
 'YFT',
 'NoF',
 'ALB',
 'ALB',
 'YFT',
 'NoF',
 'ALB',
 'ALB',
 'DOL',
 'OTHER',
 'NoF',
 'SHARK',
 'YFT',
 'SHARK',
 'ALB',
 'DOL',
 'NoF',
 'LAG',
 'ALB',
 'ALB',
 'NoF',
 'YFT',
 'ALB',
 'ALB',
 'BET',
 'ALB',
 'BET',
 'ALB',
 'NoF',
 'SHARK',
 'OTHER',
 'OTHER',
 'DOL',
 'NoF',
 'YFT',
 'ALB',
 'ALB',
 'YFT',
 'YFT',
 'YFT',
 'ALB',
 'ALB',
 'ALB',
 'ALB',
 'YFT',
 'NoF',
 'YFT',
 'ALB',
 'BET',
 'NoF',
 'YFT',
 'YFT',
 'NoF',
 'ALB',
 'OTHER',
 'NoF',
 'ALB',
 'YFT',
 'ALB',
 'ALB',
 'BET',
 'BET',
 'ALB',
 'ALB',
 'OTHER',
 'YFT',
 'OTHER',
 'ALB',
 'ALB',
 'ALB',
 'ALB',
 'YFT',
 'SHARK',
 'SHARK',
 'NoF',
 'OTHER',
 'ALB',
 'YFT',
 'ALB',
 'YFT',
 'ALB',
 'YFT',
 'ALB',
 'DOL',
 'ALB',
 'ALB',
 'NoF',
 'BET',
 'ALB',
 'YFT',
 'NoF',
 'ALB',
 'ALB',
 'ALB',
 'ALB',
 'OTHER',
 'BET',
 'YFT',
 'YFT',
 'ALB',
 'SHARK',
 'ALB',
 'ALB',
 'YFT',
 'ALB',
 'BET',
 'ALB',
 'ALB',
 'ALB',
 'YFT',
 'YFT',
 'ALB',
 'ALB',
 'NoF',
 'YFT',
 'ALB',
 'ALB',
 'ALB',
 'ALB',
 'ALB',
 'AL

In [15]:
classification_unskew, Y_unskew = convert_to_one_hot(label_unskew)

In [16]:
Y_unskew[:10]

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.]])

### reshape X for shape samples, channels, rows, columns

In [20]:
X_train = np.asarray(X)

# NEW X_TRAIN

In [17]:
X_train = np.asarray(X_unskew)

In [18]:
Y = Y_unskew

In [19]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Embedding
from keras.layers import Convolution2D, MaxPooling2D, Reshape
from keras.datasets import imdb
from keras import backend as K
import numpy

In [20]:
# Simple CNN model for CIFAR-10
import numpy
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.constraints import maxnorm
from keras.optimizers import SGD
from keras.layers.convolutional import Convolution2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras import backend as K
K.set_image_dim_ordering('th')

In [21]:
X[0].shape

(720L, 1280L, 3L)

In [22]:
num_classes=8
# Create the model
model = Sequential()
model.add(Convolution2D(64, 5, 5, input_shape=(3, 720, 1280), activation='relu', border_mode='same'))
model.add(Dropout(0.2))
model.add(Convolution2D(64, 5, 5, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Convolution2D(64, 3, 3, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Convolution2D(64, 3, 3, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Convolution2D(128, 3, 3, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Convolution2D(128, 3, 3, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Convolution2D(128, 3, 3, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Convolution2D(128, 3, 3, activation='relu', border_mode='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))


#model.add(Convolution2D(64, 3, 3, activation='relu', border_mode='same'))
#model.add(Dropout(0.2))
#model.add(Convolution2D(64, 3, 3, activation='relu', border_mode='same'))
#model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Convolution2D(128, 3, 3, activation='relu', border_mode='same'))
#model.add(Dropout(0.2))
#model.add(Convolution2D(128, 3, 3, activation='relu', border_mode='same'))
#model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Convolution2D(256, 3, 3, activation='relu', border_mode='same'))
#model.add(MaxPooling2D(pool_size=(2, 2)))
#model.add(Convolution2D(256, 3, 3, activation='relu', border_mode='same'))




model.add(Flatten())
model.add(Dropout(0.2))
model.add(Dense(68, activation='relu', W_constraint=maxnorm(3)))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu', W_constraint=maxnorm(3)))
model.add(Dropout(0.2))
model.add(Dense(16, activation='relu', W_constraint=maxnorm(3)))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))
# Compile model
epochs = 2
lrate = 0.01
decay = lrate/epochs
sgd = SGD(lr=lrate, momentum=0.9, decay=decay, nesterov=False)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
#model.fit(X_cnn, Y_batch, nb_epoch=2, batch_size=64)


In [23]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
convolution2d_1 (Convolution2D)  (None, 64, 720, 1280) 4864        convolution2d_input_1[0][0]      
____________________________________________________________________________________________________
dropout_1 (Dropout)              (None, 64, 720, 1280) 0           convolution2d_1[0][0]            
____________________________________________________________________________________________________
convolution2d_2 (Convolution2D)  (None, 64, 720, 1280) 102464      dropout_1[0][0]                  
____________________________________________________________________________________________________
maxpooling2d_1 (MaxPooling2D)    (None, 64, 360, 640)  0           convolution2d_2[0][0]            
___________________________________________________________________________________________

In [24]:
X_cnn = np.zeros([X_train.shape[0], X_train.shape[3], X_train.shape[1], X_train.shape[2]], np.uint8)
for samples in xrange(X_train.shape[0]):
    for channels in xrange(X_train.shape[3]):
        X_cnn[samples,channels,:,:] = X_train[samples,:,:,channels]

In [25]:
X_cnn.shape

(536L, 3L, 720L, 1280L)

In [26]:
def create_batch(X, Y, index, batch_size):
    X_batch = X[index:index+batch_size,:,:,:]
    X_batch = np.float16(X_batch)/255
    
    Y_batch = Y[index:index+batch_size,:]
    return X_batch, Y_batch

In [27]:
index = 0
batch_size = 1
large_batch_size = 50
large_index = 0

X_batch_large, Y_batch_large = create_batch(X_cnn, Y, large_index, large_batch_size)

while large_index < 100:
    while index<X_batch_large.shape[0]:

        X_batch = X_batch_large[index:index+batch_size,:,:,:]
        Y_batch = Y_batch_large[index:index+batch_size,:]

        model.fit(X_batch, Y_batch, nb_epoch=1, batch_size=1, verbose=False)
        #model.train_on_batch(X_batch, Y_batch)
        index += batch_size
    index = 0  
    large_index += large_batch_size
    X_batch_large, Y_batch_large = create_batch(X_cnn, Y, large_index,
                                                large_batch_size)
    print('large index: ' + str(large_index))


large index: 50
large index: 100


In [28]:
Y.shape

(536L, 8L)

In [29]:
X_test, file_array_test = load_data('F:/Kaggle/The Nature Conservancy/test_stg1/test_stg1/*')

..loading images
time elapsed: 24.5650000572


In [30]:
X_test2 = np.asarray(X_test)

In [31]:
X_cnn_test = np.zeros([X_test2.shape[0], X_test2.shape[3], X_test2.shape[1], X_test2.shape[2]], np.uint8)

for samples in xrange(X_test2.shape[0]):
    for channels in xrange(X_test2.shape[3]):
        X_cnn_test[samples,channels,:,:] = X_test2[samples,:,:,channels]

In [32]:
X_cnn_test = X_cnn_test/float(255)

In [33]:
num_predictions = 10
test_predictions = numpy.zeros([num_predictions,8])

for sample in xrange(num_predictions):
    test_predictions[sample,:] = model.predict(X_cnn_test[sample:sample+1,:,:,:])

In [34]:
test_predictions[:100,:]

array([[ 0.45499173,  0.06996741,  0.04279276,  0.02648743,  0.11002259,
         0.07945698,  0.04987249,  0.16640861],
       [ 0.45499155,  0.06996741,  0.04279279,  0.02648747,  0.11002257,
         0.07945704,  0.04987255,  0.16640863],
       [ 0.45499125,  0.06996746,  0.04279286,  0.02648754,  0.11002262,
         0.07945708,  0.04987262,  0.16640866],
       [ 0.45499134,  0.06996744,  0.04279283,  0.02648751,  0.11002259,
         0.07945707,  0.04987259,  0.16640861],
       [ 0.45499241,  0.06996734,  0.04279261,  0.02648731,  0.11002249,
         0.07945693,  0.04987235,  0.1664086 ],
       [ 0.4549911 ,  0.06996746,  0.04279287,  0.02648755,  0.11002261,
         0.07945709,  0.04987263,  0.16640863],
       [ 0.45499194,  0.06996738,  0.04279272,  0.02648739,  0.11002257,
         0.07945697,  0.04987247,  0.16640864],
       [ 0.45499155,  0.06996745,  0.04279279,  0.02648748,  0.11002258,
         0.07945705,  0.04987254,  0.16640854],
       [ 0.45499155,  0.06996743

In [43]:
Y_batch

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.]])

In [45]:
test_prediction = test_predictions

In [46]:
file_array_test = np.asarray(file_array_test)

In [47]:
# save
#test_prediction = numpy.reshape(test_prediction, [len(test_prediction), 1])
file_label = numpy.reshape(file_array_test, [len(file_array_test), 1])
labels_and_predictions = numpy.append(file_label, test_prediction, axis=1)
np.savetxt("F:/Kaggle/The Nature Conservancy/submissions/my_submission5.csv", labels_and_predictions,
           delimiter=',',fmt='%s', header= 'image,ALB,BET,DOL,LAG,NoF,OTHER,SHARK,YFT', comments='' )